from enum import Enum


class LectureType(Enum):
    EXERCISE = "Übung"
    TUTORIUM = "Tutorium"
    LECTURE = "Vorlesung"
    SEMINAR = "Seminar"
    FURTHER_LECTURE = "Sonstige Lehrveranstaltung"
    SEMINAR_PRO_SEMINAR = "Seminar/Proseminar"
    PRO_SEMINAR_EXERCISE = "Proseminar/Übung"
    PRO_SEMINAR = "Proseminar"
    LECTURE_SEMINAR = "Vorlesung/Seminar"
    SEMINAR_EXERCISE = "Seminar/Übung"
    BASIC_COURSE = "Grundkurs"
    SOURCE_STUDY_EXERCISE = "Quellenkundliche Übung"
    PRO_SEMINAR_MAIN_SEMINAR = "Proseminar/Hauptseminar"
    SEMINAR_PRO_SEMINAR_EXERCISE = "Seminar/Proseminar/Übung"
    LECTURE_EXERCISE = "Vorlesung/Übung"
    EXERCISE_TUTORIUM = "Übung/Tutorium"
    BLOCK_SEMINAR = "Blockseminar"
    EXERCISE_BLOCK_SEMINAR = "Übung/Blockseminar"
    MAIN_SEMINAR = "Hauptseminar"
    COURSE = "Kurs"
    LANGUAGE_TRAINING = "Sprachpraktische Ausbildung"
    LECTURE_WITH_STUDYACCOMPANYING_EXAMINATION = "Vorlesung mit studienbegleitender Prüfung"
    TERRAIN_SEMINAR = "Geländeseminar"
    PROJECT = "Project"
    PRAKTIKUM_EXERCISE = "Praktikum / Übung"